amixer -c0 cset name='codec_out1 mix 0 pcm0_in Switch' on
amixer -c0 cset name='media0_in Gain 0 Switch'  on
amixer -c0 cset name='media0_in Gain 0 Volume'  0%,0%
amixer -c0 cset name='media0_in Volume 0 Switch'  on
amixer -c0 cset name='media0_out mix 0 media1_in Switch' on
amixer -c0 cset name='media1_in Gain 0 Ramp Delay' 50
amixer -c0 cset name='media1_in Gain 0 Switch' off
amixer -c0 cset name='media1_in Gain 0 Volume' 80%,80%
amixer -c0 cset name='pcm0_in Gain 0 Ramp Delay' 50
amixer -c0 cset name='pcm0_in Gain 0 Switch' off
amixer -c0 cset name='pcm0_in Gain 0 Volume' 80%,80%
amixer -c0 cset name='codec_out1 Gain 0 Ramp Delay' 50
amixer -c0 cset name='codec_out1 Gain 0 Switch' off
amixer -c0 cset name='codec_out1 Gain 0 Volume' 70%,70%
amixer -c0 cset name='pcm1_out mix 0 media_loop2_in Switch' on
amixer -c0 cset name='media_loop2_out mix 0 codec_in0 Switch' on
amixer -c0 cset name='codec_in0 Gain 0 Ramp Delay' 50
amixer -c0 cset name='codec_in0 Gain 0 Switch' off
amixer -c0 cset name='codec_in0 Gain 0 Volume' 80%,80%
amixer -c0 cset name='media_loop2_out Gain 0 Ramp Delay' 50
amixer -c0 cset name='media_loop2_out Gain 0 Switch' off
amixer -c0 cset name='media_loop2_out Gain 0 Volume' 80%,80%
amixer -c0 cset name='pcm1_out Gain 0 Ramp Delay' 50
amixer -c0 cset name='pcm1_out Gain 0 Switch' off
amixer -c0 cset name='pcm1_out Gain 0 Volume' 80%,80%
